version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/testnet-faucet
hooks:
  AfterInstall:
    - location: scripts/hook.AfterInstall.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/hook.ApplicationStart.sh
      runas: ec2-user
  Applicationstop:
    - location: scripts/hook.ApplicationStop.sh
      runas: ec2-user