version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/testnet-faucet
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/hook.AfterInstall.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/hook.ApplicationStart.sh
      runas: ec2-user
  Applicationstop:
    - location: scripts/hook.ApplicationStop.sh
      runas: ec2-user